import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_features/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark, // use Clerk dark theme
        variables: {
          colorPrimary: "#111827",
          colorText: "#030303",
          colorBackground: "#ffffff",
          borderRadius: "0.75rem",
          fontFamily: "var(--font-geist-sans)",
        },
        elements: {
          card: "bg-white dark:bg-zinc-900 shadow-xl",
          formButtonPrimary:
            "bg-[#6c47ff] hover:bg-[#5a3de0] text-white rounded-full",
          formFieldInput:
            "rounded-lg border border-zinc-300 dark:border-zinc-700",
          headerTitle: "text-2xl font-semibold",
          footerActionLink: "text-[#6c47ff] hover:underline",
          userButtonPopoverCard:
            "bg-white dark:bg-zinc-900 shadow-xl rounded-xl",
          userButtonPopoverActionButton:
            "hover:bg-zinc-100 dark:hover:bg-zinc-800",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
